### ISSUE TITLE
markdownのプレビューがほしい

### ISSUE THREAD

**Issue by ken1flan** [ken1flan/everyones_notice#117]
* markdownのテキストデータを投げたら、サーバ側でhtmlに変換して返すAPI
* そもそもredcarpetをやめて、markdownのparseができるjsを入れて全部frontでやっちゃう

このへんかなぁ…どーしよ？

**Comment by a1125ts** [comment]
できれば全部redcarpetでパースしたいですね...:smile:

**Comment by a1125ts** [comment]
- きづき投稿
- 返信

**Comment by ken1flan** [comment]
テキストの内容をサーバに送って変換してもらう感じにしようかなー。

そしたら、きづき、返信、おしらせと、同じのを造り込まなくてよさげ。
